{% set name = "scorec" %}
{% set version = "2.2.7" %}
{% set build = 1 %}
{% set sha256 = "f49a23a76e848206b1bc3bd51339ce3f708cce3253b310ce186ab8545c0cbe8e" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/SCOREC/core/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
#  patches:
#    - 0001-fix-malloc-usage.patch  # [osx]
#    - 0002-fmemopen-memstream-ports-for-darwin.patch  # [osx]
  - git_url: https://github.com/SCOREC/pumi-meshes.git
    folder: pumi-meshes  

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - {{ mpi }}
    - metis 5.1
    - parmetis 4.0
    - zoltan 3

test:
  commands:
    - test -f ${PREFIX}/include/zoltan.h  # [unix]

about:
  home: https://www.scorec.rpi.edu/software.php
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The SCOREC Core is a set of C/C++ libraries for unstructured mesh simulations on supercomputers.

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - zhang-alvin
    - cekees
    - jhcollins
