{% set name = "scorec" %}
{% set version = "2.2.8" %}
{% set build = 5 %}
{% set sha256 = "5216d0d5ac031c9357a59986b1bc6f2cbdbac0356059e98a2bec78c1777a59e2" %}

{% if mpi is not defined %}
   {% set mpi = 'mpich' %}
{% endif %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/SCOREC/core/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - git_url: https://github.com/SCOREC/pumi-meshes.git
    folder: pumi-meshes

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git-lfs
    - cmake
    - make
  host:
    - {{ mpi }}
    - metis
    - parmetis
    - zoltan
  run:
    - {{ mpi }}
    - metis
    - parmetis

test:
  commands:
    - test -f ${PREFIX}/include/zoltan.h  # [unix]

about:
  home: https://www.scorec.rpi.edu/software.php
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The SCOREC Core is a set of C/C++ libraries for unstructured mesh simulations on supercomputers.

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - zhang-alvin
    - cekees
    - jhcollins
